### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by modche** [smwesten-usgs/recharge#1]
Hello,

could you help with this issue
```

The downloaded source packages are in
	‘/private/var/folders/1v/0vns_nm16w17h6np006t_g6h0000gn/T/RtmpBU0T6d/downloaded_packages’
✓  checking for file ‘/private/var/folders/1v/0vns_nm16w17h6np006t_g6h0000gn/T/RtmpBU0T6d/remotes507835f2e371/smwesten-usgs-recharge-89d947d/DESCRIPTION’ ...
─  preparing ‘recharge’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘recharge_0.1.0.tar.gz’
   
* installing *source* package ‘recharge’ ...
** using staged installation
** libs
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c rora.f -o rora.o
make: gfortran: No such file or directory
make: *** [rora.o] Error 1
ERROR: compilation failed for package ‘recharge’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/recharge’
Error: Failed to install 'recharge' from GitHub:
  (converted from warning) installation of package ‘/var/folders/1v/0vns_nm16w17h6np006t_g6h0000gn/T//RtmpBU0T6d/file50788be5ebb/recharge_0.1.0.tar.gz’ had non-zero exit status
```

**Comment by smwesten-usgs** [comment]
Hi modche,

I'm sorry you had trouble getting the package to install. The issue has to do with one or more bits of Fortran code that are used to supply the 'RORA' functionality.

My best guess is that you need to install the required 'gfortran' compiler used when building R itself on MacOS. The CRAN link to these tools is here: https://cran.r-project.org/bin/macosx/tools 

The CRAN page, in turn, links to github for a compiled version of gfortran for MacOS: https://github.com/fxcoudert/gfortran-for-macOS/releases

Keep in mind that this is really an experimental package and not necessarily my best work! I hope you can get it installed and that it is of some use to you. The underlying R codes for the PART and HYSEP methods was coded by a colleague of mine for S-plus originally and later modified to work with R. I don't claim that it has been checked thoroughly. I put these bits of code together originally because I was frustrated that there wasn't a single package out there that encapsulated all of the baseflow separation methods I was interested in exploring.

If you have improvements or fixes by all means submit a pull request!

 - Steve
